require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

# Style preferences
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Layout preferences
Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Metrics - be reasonable
Metrics/AbcSize:
  Max: 30
  Exclude:
    - "test/**/*"

Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: false  # Redis commands often have many keyword options

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - "lib/redis_ruby/commands/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"

# Naming
Naming/FileName:
  Exclude:
    - "lib/redis-rb-compat.rb"

Naming/MethodParameterName:
  AllowedNames:
    - as   # alias
    - by   # sort field
    - db   # database
    - ch   # changed
    - ef   # HNSW ef_runtime
    - ex   # expiration in seconds
    - gt   # greater than
    - id   # identifier
    - io   # IO object
    - ip   # IP address
    - k    # count/key
    - lt   # less than
    - nx   # only if not exists
    - px   # expiration in milliseconds
    - xx   # only if exists

# Redis commands use non-predicate names like SETNX, GETEX
Naming/PredicateMethod:
  Enabled: false

# Minitest
Minitest/MultipleAssertions:
  Enabled: false
